name: X45 Fitness
favicon: null
layout_spectrum: 0.5337758986279368
typography_spectrum: 0.7048854441381991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#009bcf'
    - '#ef0000'
    - '#7d0000'
    - '#197fab'
    - '#365d7f'
  brandStrength: 0.416687578195706
  lightness: 0.3183085739146918
  saturation: 0.3817463980522007
  rhythmicContrast: 0.7038905308581889
purpose: []
